chore: Enabled trailing comma for prettier
sevenwestmedia-labs/node-knex-query-executor pull request #8
Opened 2019-01-02 14:37 UTC by JakeGinnivan

2019-01-03 01:12 UTC, cyruseftos approved these changes

2019-01-03 01:49 UTC, antonjb approved these changes

2019-01-03 07:55 UTC, Tombre approved these changes

2019-01-03 12:43 UTC, cyruseftos requested changes
There seems to be a merge conflict 👍

2019-08-28 13:32 UTC, merged

2019-10-23 00:16 UTC, JakeGinnivan commented
:tada: This PR is included in version 2.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/node-knex-query-executor)
- [GitHub release](https://github.com/sevenwestmedia-labs/node-knex-query-executor/releases/tag/v2.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: